
package emisor.vista;

import emisor.controlador.ControladorEmisor;

import emisor.modelo.AbstractMensajeFactory;
import emisor.modelo.MensajeFactory;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.io.File;

import java.util.ArrayList;

import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;

import javax.sound.sampled.Clip;

import javax.sound.sampled.LineUnavailableException;

import javax.swing.BoundedRangeModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.ListSelectionModel;

import receptor.modelo.IDatosReceptor;
import receptor.modelo.IDatosReceptor;

/**
 *
 * @author Mau
 */
public class VistaEmisor extends javax.swing.JFrame implements IVistaEmisor {
    public static final int ICONO_CONECTADO_HEIGHT = 31;
    public static final int MAX_CHAR_ASUNTO = 122;
    public static final int MAX_CHAR_CUERPO = 122;
    DefaultListModel<IDatosReceptor> listModel = new DefaultListModel<IDatosReceptor>();


    /** Creates new form VistaEmisor */
    public VistaEmisor() {

        initComponents();
        this.jListDestinatarios.setModel(listModel);
        ControladorEmisor.getInstance(this);


        //this.cargarContactos();
        BoundedRangeModel modelVerticalScroll = this.jScrollPaneDestanatariosRegistrados
                                                    .getVerticalScrollBar()
                                                    .getModel();
        this.jScrollPaneConexionDestinatarios
            .getVerticalScrollBar()
            .setModel(modelVerticalScroll);
        validacionBotonesEnviarMensaje();

        jLabelCantCaracteresAsunto.setText(String.valueOf(MAX_CHAR_ASUNTO));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanelRellenoArriba = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelDestinatarios = new javax.swing.JPanel();
        jScrollPaneDestanatariosRegistrados = new javax.swing.JScrollPane();
        jListDestinatarios = new javax.swing.JList<>();
        jScrollPaneConexionDestinatarios = new javax.swing.JScrollPane();
        jPanelContainerPrincipalEstadosDestinatarios = new javax.swing.JPanel();
        jPanelContainerConexionDestinatarios = new javax.swing.JPanel();
        jPanelLlenadorEspacioEstadoDestinatarios = new javax.swing.JPanel();
        jPanelDerecha = new javax.swing.JPanel();
        jPanelBotonesArriba = new javax.swing.JPanel();
        jPanelListaContactos1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButtonListaContactos = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanelListaContactos = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonVerComprobante = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelMensajes = new javax.swing.JPanel();
        jPanelAsunto = new javax.swing.JPanel();
        jTextFieldAsunto = new javax.swing.JTextField();
        jPanelCantCaracteresAsunto = new javax.swing.JPanel();
        jLabelCantCaracteresAsunto = new javax.swing.JLabel();
        jPanelCuerpo = new javax.swing.JPanel();
        jPanelCantCaracteresCuerpo = new javax.swing.JPanel();
        jLabelCantCaracteresCuerpo = new javax.swing.JLabel();
        jScrollPaneCuerpo = new javax.swing.JScrollPane();
        jEditorCuerpo = new javax.swing.JEditorPane();
        jPanelBotonesAbajo = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelConexionDirectorio = new javax.swing.JLabel();
        jPanelConexionDirectorio = new javax.swing.JPanel();
        jPanelBotonSimple = new javax.swing.JPanel();
        jButtonEnviarSimple = new javax.swing.JButton();
        jPanelBotonAviso = new javax.swing.JPanel();
        jButtonEnviarAviso = new javax.swing.JButton();
        jPanelBotonComprobante = new javax.swing.JPanel();
        jButtonEnviarConComprobante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 700));
        setPreferredSize(new java.awt.Dimension(960, 700));

        jPanelRellenoArriba.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanelRellenoArriba.setPreferredSize(new java.awt.Dimension(1656, 50));

        javax.swing.GroupLayout jPanelRellenoArribaLayout = new javax.swing.GroupLayout(jPanelRellenoArriba);
        jPanelRellenoArriba.setLayout(jPanelRellenoArribaLayout);
        jPanelRellenoArribaLayout.setHorizontalGroup(
            jPanelRellenoArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1656, Short.MAX_VALUE)
        );
        jPanelRellenoArribaLayout.setVerticalGroup(
            jPanelRellenoArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRellenoArriba, java.awt.BorderLayout.PAGE_START);

        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(664, 150));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(878, 150));
        jPanelPrincipal.setLayout(new java.awt.BorderLayout(20, 0));

        jPanelDestinatarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receptores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanelDestinatarios.setMinimumSize(new java.awt.Dimension(600, 200));
        jPanelDestinatarios.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelDestinatarios.setLayout(new java.awt.BorderLayout());

        jScrollPaneDestanatariosRegistrados.setMinimumSize(new java.awt.Dimension(200, 50));

        jListDestinatarios.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jListDestinatarios.setModel(listModel);
        jListDestinatarios.setMaximumSize(new java.awt.Dimension(3300, 8000));
        jListDestinatarios.setMinimumSize(new java.awt.Dimension(300, 500));
        jListDestinatarios.setPreferredSize(new java.awt.Dimension(150, 1000));
        jListDestinatarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDestinatariosValueChanged(evt);
            }
        });
        jScrollPaneDestanatariosRegistrados.setViewportView(jListDestinatarios);

        jPanelDestinatarios.add(jScrollPaneDestanatariosRegistrados, java.awt.BorderLayout.CENTER);

        jScrollPaneConexionDestinatarios.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneConexionDestinatarios.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneConexionDestinatarios.setMinimumSize(new java.awt.Dimension(75, 21));
        jScrollPaneConexionDestinatarios.setPreferredSize(new java.awt.Dimension(75, 100));

        jPanelContainerPrincipalEstadosDestinatarios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContainerPrincipalEstadosDestinatarios.setLayout(new java.awt.BorderLayout());

        jPanelContainerConexionDestinatarios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContainerConexionDestinatarios.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        jPanelContainerPrincipalEstadosDestinatarios.add(jPanelContainerConexionDestinatarios, java.awt.BorderLayout.NORTH);

        jPanelLlenadorEspacioEstadoDestinatarios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLlenadorEspacioEstadoDestinatarios.setMinimumSize(new java.awt.Dimension(75, 500));
        jPanelLlenadorEspacioEstadoDestinatarios.setPreferredSize(new java.awt.Dimension(75, 500));

        javax.swing.GroupLayout jPanelLlenadorEspacioEstadoDestinatariosLayout = new javax.swing.GroupLayout(jPanelLlenadorEspacioEstadoDestinatarios);
        jPanelLlenadorEspacioEstadoDestinatarios.setLayout(jPanelLlenadorEspacioEstadoDestinatariosLayout);
        jPanelLlenadorEspacioEstadoDestinatariosLayout.setHorizontalGroup(
            jPanelLlenadorEspacioEstadoDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanelLlenadorEspacioEstadoDestinatariosLayout.setVerticalGroup(
            jPanelLlenadorEspacioEstadoDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanelContainerPrincipalEstadosDestinatarios.add(jPanelLlenadorEspacioEstadoDestinatarios, java.awt.BorderLayout.CENTER);

        jScrollPaneConexionDestinatarios.setViewportView(jPanelContainerPrincipalEstadosDestinatarios);

        jPanelDestinatarios.add(jScrollPaneConexionDestinatarios, java.awt.BorderLayout.LINE_START);

        jPanelPrincipal.add(jPanelDestinatarios, java.awt.BorderLayout.WEST);

        jPanelDerecha.setMinimumSize(new java.awt.Dimension(100, 600));
        jPanelDerecha.setPreferredSize(new java.awt.Dimension(100, 600));
        jPanelDerecha.setLayout(new java.awt.BorderLayout(20, 20));

        jPanelBotonesArriba.setMinimumSize(new java.awt.Dimension(100, 150));
        jPanelBotonesArriba.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelBotonesArriba.setLayout(new java.awt.GridLayout(0, 2));

        jPanelListaContactos1.setMinimumSize(new java.awt.Dimension(513, 150));
        jPanelListaContactos1.setPreferredSize(new java.awt.Dimension(292, 150));
        jPanelListaContactos1.setLayout(new java.awt.GridLayout(3, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelListaContactos1.add(jPanel7);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, java.awt.BorderLayout.WEST);

        jButtonListaContactos.setText("Ver Lista De Contactos Completa");
        jButtonListaContactos.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonListaContactos.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonListaContactos.setPreferredSize(new java.awt.Dimension(300, 50));
        jButtonListaContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaContactosActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonListaContactos, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(20, 66));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanelListaContactos1.add(jPanel9);

        jPanel12.setPreferredSize(new java.awt.Dimension(663, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelListaContactos1.add(jPanel12);

        jPanelBotonesArriba.add(jPanelListaContactos1);

        jPanelListaContactos.setMinimumSize(new java.awt.Dimension(513, 100));
        jPanelListaContactos.setPreferredSize(new java.awt.Dimension(292, 100));
        jPanelListaContactos.setLayout(new java.awt.GridLayout(3, 3));

        jPanel13.setPreferredSize(new java.awt.Dimension(663, 30));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelListaContactos.add(jPanel13);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        jButtonVerComprobante.setText("Ver Mensajes con Comprobante");
        jButtonVerComprobante.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonVerComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerComprobanteActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonVerComprobante, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(20, 66));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanelListaContactos.add(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelListaContactos.add(jPanel2);

        jPanelBotonesArriba.add(jPanelListaContactos);

        jPanelDerecha.add(jPanelBotonesArriba, java.awt.BorderLayout.NORTH);

        jPanelMensajes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mensajes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanelMensajes.setMinimumSize(new java.awt.Dimension(100, 159));
        jPanelMensajes.setPreferredSize(new java.awt.Dimension(100, 300));
        jPanelMensajes.setLayout(new java.awt.BorderLayout());

        jPanelAsunto.setBorder(javax.swing.BorderFactory.createTitledBorder("Asunto"));
        jPanelAsunto.setMinimumSize(new java.awt.Dimension(28, 100));
        jPanelAsunto.setPreferredSize(new java.awt.Dimension(678, 100));
        jPanelAsunto.setLayout(new java.awt.BorderLayout());

        jTextFieldAsunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAsunto.setToolTipText("Escriba aqui el asunto");
        jTextFieldAsunto.setMinimumSize(new java.awt.Dimension(4, 30));
        jTextFieldAsunto.setPreferredSize(new java.awt.Dimension(4, 30));
        jTextFieldAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAsuntoKeyReleased(evt);
            }
        });
        jPanelAsunto.add(jTextFieldAsunto, java.awt.BorderLayout.CENTER);

        jPanelCantCaracteresAsunto.setMinimumSize(new java.awt.Dimension(0, 15));
        jPanelCantCaracteresAsunto.setPreferredSize(new java.awt.Dimension(658, 15));
        jPanelCantCaracteresAsunto.setLayout(new java.awt.BorderLayout());

        jLabelCantCaracteresAsunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCantCaracteresAsunto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantCaracteresAsunto.setText("122");
        jLabelCantCaracteresAsunto.setMinimumSize(new java.awt.Dimension(18, 15));
        jLabelCantCaracteresAsunto.setPreferredSize(new java.awt.Dimension(18, 15));
        jPanelCantCaracteresAsunto.add(jLabelCantCaracteresAsunto, java.awt.BorderLayout.NORTH);

        jPanelAsunto.add(jPanelCantCaracteresAsunto, java.awt.BorderLayout.NORTH);

        jPanelMensajes.add(jPanelAsunto, java.awt.BorderLayout.NORTH);

        jPanelCuerpo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuerpo"));
        jPanelCuerpo.setMinimumSize(new java.awt.Dimension(100, 300));
        jPanelCuerpo.setPreferredSize(new java.awt.Dimension(668, 200));
        jPanelCuerpo.setLayout(new java.awt.BorderLayout());

        jPanelCantCaracteresCuerpo.setLayout(new java.awt.BorderLayout());

        jLabelCantCaracteresCuerpo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCantCaracteresCuerpo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantCaracteresCuerpo.setText("122");
        jLabelCantCaracteresCuerpo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelCantCaracteresCuerpoKeyReleased(evt);
            }
        });
        jPanelCantCaracteresCuerpo.add(jLabelCantCaracteresCuerpo, java.awt.BorderLayout.PAGE_END);

        jPanelCuerpo.add(jPanelCantCaracteresCuerpo, java.awt.BorderLayout.NORTH);

        jEditorCuerpo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jEditorCuerpo.setToolTipText("Escriba aqui el cuerpo");
        jEditorCuerpo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEditorCuerpoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEditorCuerpoKeyReleased(evt);
            }
        });
        jScrollPaneCuerpo.setViewportView(jEditorCuerpo);

        jPanelCuerpo.add(jScrollPaneCuerpo, java.awt.BorderLayout.CENTER);

        jPanelMensajes.add(jPanelCuerpo, java.awt.BorderLayout.CENTER);

        jPanelDerecha.add(jPanelMensajes, java.awt.BorderLayout.CENTER);

        jPanelPrincipal.add(jPanelDerecha, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        jPanelBotonesAbajo.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanelBotonesAbajo.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanelBotonesAbajo.setLayout(new java.awt.GridLayout(1, 4, 20, 20));

        jPanel8.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabelConexionDirectorio.setText("jLabel1");

        jPanelConexionDirectorio.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout jPanelConexionDirectorioLayout = new javax.swing.GroupLayout(jPanelConexionDirectorio);
        jPanelConexionDirectorio.setLayout(jPanelConexionDirectorioLayout);
        jPanelConexionDirectorioLayout.setHorizontalGroup(
            jPanelConexionDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanelConexionDirectorioLayout.setVerticalGroup(
            jPanelConexionDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelConexionDirectorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConexionDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelConexionDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConexionDirectorio))
                .addContainerGap())
        );

        jPanelBotonesAbajo.add(jPanel8);

        jPanelBotonSimple.setPreferredSize(new java.awt.Dimension(100, 100));

        jButtonEnviarSimple.setText("Enviar mensaje Simple");
        jButtonEnviarSimple.setMaximumSize(new java.awt.Dimension(120, 40));
        jButtonEnviarSimple.setMinimumSize(new java.awt.Dimension(120, 40));
        jButtonEnviarSimple.setPreferredSize(new java.awt.Dimension(120, 40));
        jButtonEnviarSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarSimpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonSimpleLayout = new javax.swing.GroupLayout(jPanelBotonSimple);
        jPanelBotonSimple.setLayout(jPanelBotonSimpleLayout);
        jPanelBotonSimpleLayout.setHorizontalGroup(
            jPanelBotonSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonSimpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEnviarSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBotonSimpleLayout.setVerticalGroup(
            jPanelBotonSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonSimpleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonEnviarSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBotonesAbajo.add(jPanelBotonSimple);

        jPanelBotonAviso.setPreferredSize(new java.awt.Dimension(100, 100));

        jButtonEnviarAviso.setText("Enviar mensaje con alerta");
        jButtonEnviarAviso.setMaximumSize(new java.awt.Dimension(140, 40));
        jButtonEnviarAviso.setMinimumSize(new java.awt.Dimension(140, 40));
        jButtonEnviarAviso.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonEnviarAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarAvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonAvisoLayout = new javax.swing.GroupLayout(jPanelBotonAviso);
        jPanelBotonAviso.setLayout(jPanelBotonAvisoLayout);
        jPanelBotonAvisoLayout.setHorizontalGroup(
            jPanelBotonAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEnviarAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBotonAvisoLayout.setVerticalGroup(
            jPanelBotonAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonAvisoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonEnviarAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelBotonesAbajo.add(jPanelBotonAviso);

        jPanelBotonComprobante.setPreferredSize(new java.awt.Dimension(100, 100));

        jButtonEnviarConComprobante.setText("Enviar mensaje con comprobante");
        jButtonEnviarConComprobante.setMaximumSize(new java.awt.Dimension(173, 40));
        jButtonEnviarConComprobante.setMinimumSize(new java.awt.Dimension(173, 40));
        jButtonEnviarConComprobante.setPreferredSize(new java.awt.Dimension(173, 40));
        jButtonEnviarConComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarConComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonComprobanteLayout = new javax.swing.GroupLayout(jPanelBotonComprobante);
        jPanelBotonComprobante.setLayout(jPanelBotonComprobanteLayout);
        jPanelBotonComprobanteLayout.setHorizontalGroup(
            jPanelBotonComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonComprobanteLayout.createSequentialGroup()
                .addComponent(jButtonEnviarConComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBotonComprobanteLayout.setVerticalGroup(
            jPanelBotonComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonComprobanteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonEnviarConComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelBotonesAbajo.add(jPanelBotonComprobante);

        getContentPane().add(jPanelBotonesAbajo, java.awt.BorderLayout.PAGE_END);

        pack();
    }//GEN-END:initComponents

    private void jButtonVerComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerComprobanteActionPerformed
        jButtonVerComprobante.setEnabled(false);
        JFrame vistaComprobantes = new VistaComprobantes();
        vistaComprobantes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vistaComprobantes.setVisible(true);


        vistaComprobantes.addWindowListener(new WindowAdapter() {


            @Override
            public void windowClosing(WindowEvent windowEvent) {
                jButtonVerComprobante.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButtonVerComprobanteActionPerformed

    private void jButtonEnviarConComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarConComprobanteActionPerformed
        ControladorEmisor.getInstance().enviarMensajeConComprobante(getAsunto(), getCuerpo(), this.getDestinatarios());
       
    }//GEN-LAST:event_jButtonEnviarConComprobanteActionPerformed

    private void jButtonEnviarSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarSimpleActionPerformed
        ControladorEmisor.getInstance().enviarMensajeNormal(getAsunto(), getCuerpo(), this.getDestinatarios());
    }//GEN-LAST:event_jButtonEnviarSimpleActionPerformed

    private void jButtonEnviarAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarAvisoActionPerformed
        ControladorEmisor.getInstance().enviarMensajeConAlerta(getAsunto(), getCuerpo(), this.getDestinatarios());
    }//GEN-LAST:event_jButtonEnviarAvisoActionPerformed

    private void jEditorCuerpoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorCuerpoKeyTyped
        
    }//GEN-LAST:event_jEditorCuerpoKeyTyped

    private void jEditorCuerpoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorCuerpoKeyReleased
        String texto = this.jEditorCuerpo.getText();

        if (texto.length() > MAX_CHAR_CUERPO) {
            texto = texto.substring(0, MAX_CHAR_CUERPO);
            jEditorCuerpo.setText(texto);
        }

        jLabelCantCaracteresCuerpo.setText(String.valueOf(MAX_CHAR_CUERPO - texto.length()));

        validacionBotonesEnviarMensaje();

        validacionBotonesEnviarMensaje();
    }//GEN-LAST:event_jEditorCuerpoKeyReleased

    private void jTextFieldAsuntoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoKeyReleased
        String texto = this.jTextFieldAsunto.getText();

        if (texto.length() > MAX_CHAR_ASUNTO) {
            texto = texto.substring(0, MAX_CHAR_ASUNTO);
            jTextFieldAsunto.setText(texto);
        }

        jLabelCantCaracteresAsunto.setText(String.valueOf(MAX_CHAR_ASUNTO - texto.length()));

        validacionBotonesEnviarMensaje();
        
    }//GEN-LAST:event_jTextFieldAsuntoKeyReleased

    private void jListDestinatariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDestinatariosValueChanged
        validacionBotonesEnviarMensaje();
    }//GEN-LAST:event_jListDestinatariosValueChanged

    private void jLabelCantCaracteresCuerpoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelCantCaracteresCuerpoKeyReleased
        
    }//GEN-LAST:event_jLabelCantCaracteresCuerpoKeyReleased

    private void jButtonListaContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaContactosActionPerformed
        jButtonListaContactos.setEnabled(false);
        JFrame vistaContactos = new VistaContactos();
        vistaContactos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vistaContactos.setVisible(true);

        vistaContactos.addWindowListener(new WindowAdapter() {


            @Override
            public void windowClosing(WindowEvent windowEvent) {
                jButtonListaContactos.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButtonListaContactosActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaEmisor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaEmisor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaEmisor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaEmisor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new VistaEmisor().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarAviso;
    private javax.swing.JButton jButtonEnviarConComprobante;
    private javax.swing.JButton jButtonEnviarSimple;
    private javax.swing.JButton jButtonListaContactos;
    private javax.swing.JButton jButtonVerComprobante;
    private javax.swing.JEditorPane jEditorCuerpo;
    private javax.swing.JLabel jLabelCantCaracteresAsunto;
    private javax.swing.JLabel jLabelCantCaracteresCuerpo;
    private javax.swing.JLabel jLabelConexionDirectorio;
    private javax.swing.JList<IDatosReceptor> jListDestinatarios;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAsunto;
    private javax.swing.JPanel jPanelBotonAviso;
    private javax.swing.JPanel jPanelBotonComprobante;
    private javax.swing.JPanel jPanelBotonSimple;
    private javax.swing.JPanel jPanelBotonesAbajo;
    private javax.swing.JPanel jPanelBotonesArriba;
    private javax.swing.JPanel jPanelCantCaracteresAsunto;
    private javax.swing.JPanel jPanelCantCaracteresCuerpo;
    private javax.swing.JPanel jPanelConexionDirectorio;
    private javax.swing.JPanel jPanelContainerConexionDestinatarios;
    private javax.swing.JPanel jPanelContainerPrincipalEstadosDestinatarios;
    private javax.swing.JPanel jPanelCuerpo;
    private javax.swing.JPanel jPanelDerecha;
    private javax.swing.JPanel jPanelDestinatarios;
    private javax.swing.JPanel jPanelListaContactos;
    private javax.swing.JPanel jPanelListaContactos1;
    private javax.swing.JPanel jPanelLlenadorEspacioEstadoDestinatarios;
    private javax.swing.JPanel jPanelMensajes;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRellenoArriba;
    private javax.swing.JScrollPane jScrollPaneConexionDestinatarios;
    private javax.swing.JScrollPane jScrollPaneCuerpo;
    private javax.swing.JScrollPane jScrollPaneDestanatariosRegistrados;
    private javax.swing.JTextField jTextFieldAsunto;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getAsunto() {
        return this.jTextFieldAsunto.getText();
    }

    @Override
    public String getCuerpo() {
        return this.jEditorCuerpo.getText();
    }

    @Override
    public ArrayList<IDatosReceptor> getDestinatarios() {
        return new ArrayList<IDatosReceptor>(this.jListDestinatarios.getSelectedValuesList());
    }

    @Override
    public void mostrarErrorEmisorContactos() {
        JOptionPane.showMessageDialog(this,
                                      "Error: no se pudo encontrar el archivo con los datos del emisor o de la agenda",
                                      "ERROR", JOptionPane.ERROR_MESSAGE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }


    public void envioExitoso() {
        limpiarDatosEnvio();
        JOptionPane.showConfirmDialog(this, "Mensaje enviado", "Exito", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void limpiarDatosEnvio(){
        this.jTextFieldAsunto.setText("");
        this.jEditorCuerpo.setText("");
        this.jListDestinatarios.clearSelection();
    }

    public void cargarContactos(Collection<IDatosReceptor> destinatariosRegistrados) {
        Iterator<IDatosReceptor> it = destinatariosRegistrados.iterator();

        HashMap<String, IDatosReceptor> seleccionadosHashmap = new HashMap<String, IDatosReceptor>();
        ArrayList<IDatosReceptor> seleccionadosArrayList =
            new ArrayList<IDatosReceptor>(this.jListDestinatarios.getSelectedValuesList());


        //para hacer ruiditos de conectado y desconectado
        while (it.hasNext()) {
            IDatosReceptor r = it.next();
            int posrviejo = this.listModel.indexOf(r);
            if (posrviejo != -1) {
                IDatosReceptor rviejo = listModel.getElementAt(posrviejo);

                if (rviejo.isConectado() && !r.isConectado()) {
                    try {
                        AudioInputStream audioInputStream;
                        Clip clip;
                        audioInputStream =
                            AudioSystem.getAudioInputStream(new File("alguiensedesconecto.wav").getAbsoluteFile());
                        clip = AudioSystem.getClip();
                        clip.open(audioInputStream);
                        clip.start();
                    } catch (Exception e) {
                        System.out.println("problemas de audio");
                        //e.printStackTrace();

                    }
                }
                //sonido se desconecto
                else if (!rviejo.isConectado() && r.isConectado()) {
                    try {
                        AudioInputStream audioInputStream;
                        Clip clip;
                        audioInputStream =
                            AudioSystem.getAudioInputStream(new File("alguienseconecto.wav").getAbsoluteFile());

                        clip = AudioSystem.getClip();

                        clip.open(audioInputStream);
                        clip.start();
                    } catch (Exception e) {
                        System.out.println("problemas de audio");
                        //e.printStackTrace();

                    }
                }
                //sonido de se conecto
            } else { //es nuevo merece sonidito

                try {
                    AudioInputStream audioInputStream;
                    Clip clip;
                    audioInputStream =
                        AudioSystem.getAudioInputStream(new File("alguienseconecto.wav").getAbsoluteFile());
                    clip = AudioSystem.getClip();
                    clip.open(audioInputStream);
                    clip.start();
                } catch (Exception e) {
                    System.out.println("problemas de audio");
                    //e.printStackTrace();

                }
            }


        }

        it =
            ControladorEmisor.getInstance()
            .getContactos(); //reset por que lo gaste arriba. no peudo hacer to  do junto xq ahi abajo no hay nada en el listmodel


        //fin de eso


        for (IDatosReceptor r : seleccionadosArrayList) {
            seleccionadosHashmap.put(r.getUsuario(), r);
        }


        listModel.clear();
        this.deleteAllPanelesEstadoConexion();
        int i = 0;
        while (it.hasNext()) { //por ahora tomamos que los nuevos son los de abajo aunque no esten alfabeticamente asi
            IDatosReceptor receptor = it.next();

            this.cargarContacto(receptor);
            //System.out.println("Se agrego en lista "+receptor);
            if (seleccionadosHashmap.get(receptor.getUsuario()) != null)
                this.jListDestinatarios.addSelectionInterval(i, i);
            i++;
        }
        this.cambiarAltoPanelEstadoConexion(i); //cambia el alto 1 sola vez
        this.jScrollPaneConexionDestinatarios.validate();
        this.jScrollPaneConexionDestinatarios.repaint();
        this.jScrollPaneDestanatariosRegistrados.validate();
        this.jScrollPaneDestanatariosRegistrados.repaint();
        this.validate();
        this.repaint();

        //        System.out.println("CARGARCONTACTOS");
    }


    /**
     * Pre: !this.listModel.contains(receptor)
     * @param receptor
     */
    public void cargarContacto(IDatosReceptor receptor) {
        this.listModel.addElement(receptor);
        System.out.println(listModel.toString());
        //System.out.println("Se agrego "+ receptor);
        this.addPanelEstadoConexion(receptor.isConectado());

        this.jScrollPaneDestanatariosRegistrados.validate(); //SDMOP
        this.jScrollPaneDestanatariosRegistrados.repaint(); //SDMOP
    }


    public void validacionBotonesEnviarMensaje() {
        boolean mensajeOK =
            !(jTextFieldAsunto.getText()
                                              .trim()
                                              .equals("") || jEditorCuerpo.getText()
                                                                          .trim()
                                                                          .equals("") ||
              jListDestinatarios.isSelectionEmpty());
        jButtonEnviarSimple.setEnabled(mensajeOK);
        jButtonEnviarAviso.setEnabled(mensajeOK);
        jButtonEnviarConComprobante.setEnabled(mensajeOK);
    }

    private boolean oldEstadoDirectorio = true;

    @Override
    public void updateConectado(boolean estado) {
        if (estado != oldEstadoDirectorio || estado)
            if (estado) {
                this.jLabelConexionDirectorio.setText("Conectado");
                this.jPanelConexionDirectorio.setBackground(Color.green);
                oldEstadoDirectorio = estado;
            } else {
                this.jLabelConexionDirectorio.setText("Desconectado");
                this.jPanelConexionDirectorio.setBackground(Color.gray);
                this.deleteAllPanelesEstadoConexion();
                this.agregarTodosPanelesEstadoIncierto();

                this.jScrollPaneConexionDestinatarios.validate();
                this.jScrollPaneConexionDestinatarios.repaint();
                this.jScrollPaneDestanatariosRegistrados.validate();
                this.jScrollPaneDestanatariosRegistrados.repaint();
                this.validate();
                this.repaint();
                oldEstadoDirectorio = estado;
            }
    }

    public void agregarTodosPanelesEstadoIncierto() {
        int i = 0;
        while (i < this.listModel.getSize()) {
            jPanelContainerConexionDestinatarios.add(new PanelEstadoConexion());

            i++;
        }

        this.cambiarAltoPanelEstadoConexion(i); //cambia el alto 1 sola vez
        this.jScrollPaneConexionDestinatarios.validate();
        this.jScrollPaneConexionDestinatarios.repaint();
        this.jScrollPaneDestanatariosRegistrados.validate();
        this.jScrollPaneDestanatariosRegistrados.repaint();
        this.validate();
        this.repaint();
    }

    public void addPanelEstadoConexion(boolean conectado) { //solo los añade pero no cambia el alto del panel

        jPanelContainerConexionDestinatarios.add(new PanelEstadoConexion(conectado));
    }


    public void cambiarAltoPanelEstadoConexion(int cantDestRegistrados) { //cambia el alto del panel
        double anchoAct = jPanelContainerConexionDestinatarios.getPreferredSize().getWidth(); //no cambia
        double altoAct = cantDestRegistrados * ICONO_CONECTADO_HEIGHT;
        Dimension nuevaDimension = new Dimension((int) anchoAct, (int) altoAct);
        jPanelContainerConexionDestinatarios.setMinimumSize(nuevaDimension);
        jPanelContainerConexionDestinatarios.setPreferredSize(nuevaDimension);
    }

    public void deleteAllPanelesEstadoConexion() {
        jPanelContainerConexionDestinatarios.removeAll(); //limpia los estados de receptores anteriores

        Dimension nada = new Dimension(1, 1);
        jPanelContainerConexionDestinatarios.setMinimumSize(nada);
        jPanelContainerConexionDestinatarios.setPreferredSize(nada);

        validate();
        repaint();

    }

    @Override
    public void mostrarErrorServidorNoDisponible() {
        limpiarDatosEnvio();
        JOptionPane.showMessageDialog(this, "El mensaje sera enviado proximamente", "Envio programado", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void setNombreUsuario(String nombreEmisor) {
        this.setTitle("Emisor: "+nombreEmisor);
    }
}


