package receptor.vista;

import emisor.modelo.Mensaje;

import java.awt.event.WindowEvent;

import java.io.File;

import java.io.IOException;

import javax.sound.sampled.AudioInputStream;

import javax.sound.sampled.AudioSystem;

import javax.sound.sampled.Clip;

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

import javax.swing.DefaultListModel;

import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;

import receptor.controlador.ControladorReceptor;

/**
 *
 * @author Mau
 */
public class VistaReceptor extends javax.swing.JFrame implements IVistaReceptor {
    DefaultListModel<Mensaje> listModel = new DefaultListModel<Mensaje>();
    private boolean sonando = false;
    private Clip clip = null;

    /** Creates new form VistaReceptor */
    public VistaReceptor() {
        
        initComponents();
        ControladorReceptor.getInstance(this);
        this.jListMensajes.setCellRenderer(new RendererMensajesRecibidos());
        this.jListMensajes.setSelectionModel(new DefaultListSelectionModel(){

        @Override
        public void setSelectionInterval(int index0, int index1) {
            super.setSelectionInterval(-1, -1);
        }
        @Override
        public void addSelectionInterval(int index0, int index1) {
            super.setSelectionInterval(-1, -1);
        }
        });
        this.jListMensajes.setFixedCellHeight(300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanelMensajes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMensajes = new javax.swing.JList<>();
        jPanelAbajo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jButtonSilenciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recepcion de Mensajes");
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jPanelMensajes.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensajes"));
        jPanelMensajes.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanelMensajes.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanelMensajes.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 50));

        jListMensajes.setModel(listModel);
        jListMensajes.setMaximumSize(new java.awt.Dimension(3300, 8000));
        jListMensajes.setMinimumSize(new java.awt.Dimension(300, 500));
        jListMensajes.setPreferredSize(new java.awt.Dimension(150, 1000));
        jScrollPane1.setViewportView(jListMensajes);

        jPanelMensajes.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelAbajo.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelAbajo.add(jPanel2, java.awt.BorderLayout.WEST);

        jProgressBar1.setForeground(new java.awt.Color(254, 0, 0));
        jProgressBar1.setMaximum(1);

        jLabel1.setText("Indicador de alerta:");

        jButtonSilenciar.setText("Silenciar");
        jButtonSilenciar.setMaximumSize(new java.awt.Dimension(53, 40));
        jButtonSilenciar.setMinimumSize(new java.awt.Dimension(53, 40));
        jButtonSilenciar.setPreferredSize(new java.awt.Dimension(53, 40));
        jButtonSilenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilenciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonSilenciar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonSilenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAbajo.add(jPanel3, java.awt.BorderLayout.CENTER);
        jPanelAbajo.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanelMensajes.add(jPanelAbajo, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelMensajes, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButtonSilenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilenciarActionPerformed
        this.jProgressBar1.setValue(0);
        this.clip.stop();
        this.sonando = false;
    }//GEN-LAST:event_jButtonSilenciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaReceptor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaReceptor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaReceptor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaReceptor.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new VistaReceptor().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSilenciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Mensaje> jListMensajes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAbajo;
    private javax.swing.JPanel jPanelMensajes;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void activarAlerta() {
        if(!sonando){
            this.jProgressBar1.setValue(1);
            this.repaint();
            this.sonando = true;
            String soundName = "alert.wav";    
            AudioInputStream audioInputStream;
            this.sonando = true;
            try {
                audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
                this.clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.loop(99999999);
                    clip.start();
                   
            } catch (IOException | UnsupportedAudioFileException e) {
                //nada
            } catch (LineUnavailableException e) {
            }
            
        }
            
            
        
    }


    @Override
    public void agregarMensaje(Mensaje mensaje) {
        this.listModel.add(0,mensaje);
        this.repaint();
    }

    @Override
    public void mostrarErrorNoReceptor() {
        JOptionPane.showMessageDialog(this, "Error: no se pudo encontrar el archivo con los datos del receptor", "ERROR",
                                      JOptionPane.ERROR_MESSAGE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
}
